apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-inventory
  description: 在庫管理業務のマイクロサービスです
  labels:
    app: inventory
  annotations:
    github.com/project-slug: quarkusdroneshop/inventory
spec:
  type: website
  owner: user:default/nmushino
  lifecycle: production