apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-inventory
  description: 在庫管理業務のマイクロサービスです
  labels:
    app: inventory
  annotations:
    github.com/project-slug: quarkusdroneshop/quarkusdroneshop-inventory
    backstage.io/kubernetes-id: quarkusdroneshop-inventory
    backstage.io/kubernetes-cluster: b-cluster
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=quarkusdroneshop-inventory
    tektonci.io/pipeline: build-and-push-quarkusdroneshop-inventory
    tektonci.io/pipelineNamespace: quarkusdroneshop-cicd
    tekton.dev/cicd: "true"
    janus-idp.io/tekton: "true"
spec:
  type: microservice
  owner: user:default/nmushino
  lifecycle: production
  system: b-cluster
  dependsOn:
    - resource:droneshopdb-postgresql
    - resource:shop-cluster-kafka
    - resource:shop-asite-inventory-in
  consumesApis:
    - kafka-shop-asite-inventory-in
  providesApis:
    - kafka-inventory-out
